import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Changed from Geist to Inter
import "./globals.css";

const inter = Inter({
  variable: "--font-inter", // Variable name change
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-2 right-4 text-xs text-gray-400">
          Murat ÖRGÜT
        </div>
      </body>
    </html>
  );
}
